services:

  webapp:
    build:
      args:
        - PIP_VERSION=${WEBAPP_PIP_VERSION:-23.1.2}
        - POETRY_VERSION=${WEBAPP_POETRY_VERSION:-1.5.1}
        - PYTHON_VERSION=${WEBAPP_PYTHON_VERSION:-3.11}
        - VERSION=${WEBAPP_VERSION:-dev}
      context: .
    container_name: cmms.webapp
    image: webapp:latest
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      ADMINS: ${ADMINS}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_USE_SSL: ${EMAIL_USE_SSL}
      DEBUG_EMAIL: ${DEBUG_EMAIL}
      DEBUG_PASSWORDS: ${DEBUG_PASSWORDS}
      DEBUG_DEFAULT_PASSWORD: ${DEBUG_DEFAULT_PASSWORD}
    networks:
      - cmms
    ports:
      - "8000:8000"
    volumes:
      - .local/services/webapp:/app/:ro
    init: true

networks:
  cmms:
    name: cmms.network
    driver: bridge