# Generated by Django 5.1.4 on 2024-12-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("deadline", models.DateTimeField(verbose_name="Deadline")),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Closed at"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("planned", "Zadania planowe"), ("failure", "Awarie")],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Niski"),
                            ("medium", "Średni"),
                            ("high", "Wysoki"),
                        ],
                        max_length=50,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=2048, verbose_name="Description"),
                ),
                (
                    "attachments",
                    models.FileField(blank=True, null=True, upload_to="attachments/"),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Comments"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buildings.building",
                        verbose_name="Building",
                    ),
                ),
            ],
        ),
    ]
