# Generated by Django 5.1.4 on 2025-01-08 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_person",
            field=models.ManyToManyField(
                related_name="assigned_person",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assigned person",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="attachments",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="attachments/",
                verbose_name="Attachments",
            ),
        ),
        migrations.RemoveField(
            model_name="task",
            name="building",
        ),
        migrations.AlterField(
            model_name="task",
            name="comments",
            field=models.TextField(
                blank=True, max_length=2048, null=True, verbose_name="Comments"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="building",
            field=models.ManyToManyField(
                related_name="building",
                to="buildings.building",
                verbose_name="Building",
            ),
        ),
    ]
