# Generated by Django 5.1.4 on 2025-02-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_remove_task_attachments_attachment_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status_field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("confirmed", "Wykonano"),
                    ("declined", "Wykonanie nie potwierdzone"),
                    ("accepted", "Wykonanie potwierdzone"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
