# Generated by Django 5.1.4 on 2025-02-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cmmsuser",
            name="manager",
        ),
        migrations.AddField(
            model_name="cmmsuser",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
    ]
