# Generated by Django 5.1.4 on 2025-02-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_cmmsuser_manager_cmmsuser_is_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmmsuser",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="Jest menedżerem"),
        ),
    ]
